import { readFileSync, writeFileSync, existsSync } from 'fs';

export function loadEnvFile(envFilePath) {
  if (!existsSync(envFilePath)) return {};
  const content = readFileSync(envFilePath, 'utf-8');
  const env = {};
  for (const line of content.split('\n')) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;
    const eqIndex = trimmed.indexOf('=');
    if (eqIndex > 0) {
      const key = trimmed.slice(0, eqIndex).trim();
      const value = trimmed.slice(eqIndex + 1).trim();
      env[key] = value;
    }
  }
  return env;
}

export function saveEnvFile(envFilePath, env) {
  const lines = [];
  lines.push('# OpenClawd Configuration');
  lines.push('# Generated by Settings UI');
  lines.push('');
  for (const [key, value] of Object.entries(env)) {
    if (value) lines.push(`${key}=${value}`);
  }
  writeFileSync(envFilePath, lines.join('\n') + '\n');
}
